# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aogallo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: order-service
frameworkVersion: "4"
plugins:
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
environment:
  SQS_QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/order-events
iam:
  role:
    statements:
      - Effect: Allow
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:${aws:region}:${aws:accountId}:order-events
custom:
  localstack:
    stages:
      - local
    endpointFile: ${env:LOCALSTACK_ENDPOINT_FILE, './localstack-endpoints.json'}
    host: ${env:LOCALSTACK_HOST, 'http://localhost'}
    lambda:
      mountCode: false
      debug: true
functions:
  createOrder:
    handler: ./src/handlers/createOrder.handler
  getOrderById:
    handler: ./src/handlers/getOrderById.handler
