name: LocalStack and Mailhog
services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      SERVICES: dynamodb,sqs,s3,cognito,ses,lambda,apigateway,sesv2,cloudformation,ssm,logs,iam,cognito-idp
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      EDGE_PORT: 4566
      DATA_DIR: /var/lib/localstack/data
      PERSISTENCE: 1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  localstack-data:
